Endpoint
haroldmud/expense-tracker pull request #1
Opened 2023-09-20 09:49 UTC by haroldmud

2023-09-21 08:13 UTC, IbrahimBagalwa requested changes
Great job @haroldmud 
I left comments to improve the code base

2023-09-21 08:13 UTC, IbrahimBagalwa commented on src/budget/budget.controller.ts
> +    @Body('priority') priority: string,
Why this?

2023-09-21 08:13 UTC, IbrahimBagalwa commented on src/budget/budget.service.ts
>    }
why this here you can only use the patch in your controller instead of doing all of this

2023-09-21 08:13 UTC, IbrahimBagalwa commented on src/budget/budget.controller.ts
> +  @Put(':id')
Change this to patch

2023-09-21 08:13 UTC, IbrahimBagalwa commented on src/budget/budget.controller.ts
> +    @Body('description') description: string,
Can you make you body generic here

2023-09-25 08:58 UTC, haroldmud commented on src/budget/budget.controller.ts
> +  @Put(':id')
This one gets one item but about Patch, it is not that effective yet, I'll need to learn more about it. and then apply it

2023-09-25 08:59 UTC, haroldmud commented on src/budget/budget.controller.ts
> +    @Body('description') description: string,
Done

2023-09-25 08:59 UTC, haroldmud commented on src/budget/budget.controller.ts
> +    @Body('priority') priority: string,
Done

2023-09-25 22:01 UTC, IbrahimBagalwa requested changes
Apply again the request changes

2023-09-25 22:01 UTC, IbrahimBagalwa commented on src/budget/budget.controller.ts
> +    },
Can you use change this object and make it dynamic like 
```js 
create(@Body() budget: Budget): Promise<BudgetDocument>
```

2023-09-25 22:01 UTC, IbrahimBagalwa commented on src/budget/budget.controller.ts
>    }
can you await there

2023-09-25 22:01 UTC, IbrahimBagalwa commented on src/budget/budget.controller.ts
> +    return this.budgetService.findOne(id);
```suggestion
  findOne(@Param('id') id: string): Promise<BudgetDocument> {
    return await this.budgetService.findOne(id);
```
here as well

2023-09-25 22:01 UTC, IbrahimBagalwa commented on src/budget/budget.controller.ts
> +    },
```suggestion
    Body: {
      item: string;
      budget: number;
      category: string;
      priority: string;
      description: string;
    },
```
here as well you can use `Budget`

2023-10-01 13:40 UTC, merged